services:
  db:
    image: postgres:latest
    container_name: OdontoGate_DB
    environment:
      POSTGRES_USER: Administrador
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: OdontoGate_DB
    ports:
      - "5432:5432"
